version: '3.8'
services:
  db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 12345
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/12345@//localhost:1521/XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@db:1521:xe
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      db:
        condition: service_healthy

  ui:
    build:
      context: ./ui
    depends_on:
      - backend
    environment:
      DISPLAY: host.docker.internal:0
